model:
  base_learning_rate: 2.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 0
    cond_stage_key: 1
    conditioning_key: concat
    image_size: 32
    channels: 3
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 6
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: /ifs/loni/groups/loft/qinyang/ADNI_M0generation/M0_generation/models/first_stage_models/vq-f4/model.ckpt
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__
data:
  target: main.DataModuleFromConfigM0
  params:
    batch_size: 4
    num_workers: 24
    wrap: false
    train:
      target: data.M0_Control.data_utils_M0.Combined_M0_Dataset_VCID_Mayo_Train
      params:
        condition: control
        normalize: Norm4096_0center
    validation:
      target: data.M0_Control.data_utils_M0.Combined_M0_Dataset_VCID_Mayo_Valid
      params:
        condition: control
        normalize: Norm4096_0center
other:
  trainer:
    check_val_every_n_epoch: 5
